import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

import { useEffect, useState } from 'react'
import {useRouter} from 'next/router'
// import ListMasakan from '../components/listMasakan'
import axios from "axios"

export const getStaticProps = async () =>{
  const [detail, setDetail] = useState(null);

  await axios.get(`https://masak-apa-tomorisakura.vercel.app/api/recipe/${key}`)
    .then(res=>{
      setDetail(res.data.results);
      console.log(res.data.results)
    })
    .catch(err =>{
      console.log(err.message);
  })

  return{
    props : {details: detail}
  }

}

const Detail = ({details}) =>{

  const router = useRouter();
  const {key} = router.query;

  // const [resep, setResep] = useState(null);

  // const fetchData = async () =>{
  //   await axios.get(`https://masak-apa-tomorisakura.vercel.app/api/recipe/${key}`)
  //     .then(res=>{
  //       setResep(res.data.results);
  //       // console.log(res.data.results)
  //     })
  //     .catch(err =>{
  //       console.log(err.message);
  //   })
  // }

  // useEffect( ()=>{
    
  //   fetchData();

  // },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>{key}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Masak Apa Hari Ini?
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        {/* <resep data={resep} /> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Detail;
